name: VPS-SSH2

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update & install
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y openssh-server curl wget unzip jq
          sudo service ssh start
          echo "root:password123" | sudo chpasswd
          echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
          sudo service ssh restart

      - name: Install Ngrok (latest)
        run: |
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          tar -xvzf ngrok-v3-stable-linux-amd64.tgz
          sudo mv ngrok /usr/local/bin/
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start Ngrok Tunnel
        run: |
          nohup ngrok tcp 22 --log=stdout > ngrok.log &
          sleep 5

      - name: Show SSH Command
        run: |
          TUNNEL=$(curl -s localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          HOST=$(echo $TUNNEL | sed -e "s/tcp:\/\///" -e "s/:/ -p /")
          echo "========================================"
          echo " COPY THIS COMMAND INTO TERMINUS / SSH "
          echo ""
          echo "ssh root@$HOST"
          echo ""
          echo "Password: password123"
          echo "========================================"
